# Site settings
title: The digital presence of jdm7dv or Jonathan Moor
description: A blog about the documenting of jdm7dv. Social Media archives and in the works.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://jdm7dv.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jonathan Moor
user_description: Ubuntu Studio Team Member, Google Partner, Member of 'Artists and Machine Intelligence' 
user_title: Ableton Organizer, Artist, Engineer.
email: jonathanmoore@computer.org
twitter_username: jdm7dv
github_username:  jdm7dv
gplus_username:  +JonathanmooreNet1

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
